// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import { Script, console } from "forge-std/Script.sol";
import { MockOracle } from "../src/MockOracle.sol";
import { ControlledCollateral } from "../src/ControlledCollateral.sol";
import { LendingPool } from "../src/LendingPool.sol";

/// @title AttackScenarioPart1 - executes the first 6 steps of the oracle
///         manipulation attack. All transactions succeed. Generates on-chain
///         events that the defense system detects.
///
/// Steps:
///   1. Mint 1000 collateral to attacker
///   2. Approve pool
///   3. Deposit 100 collateral
///   4. Borrow 75 (max at $1)
///   5. Manipulate oracle to $1.80
///   6. Borrow 60 more (total debt = 135)
///
/// The withdrawal (step 7) is NOT included — it would revert via the
/// SecurityController, which is the defense working. The defense system
/// detects the attack from the events generated by steps 1-6 and simulates
/// the withdrawal consequence.
///
/// Usage:
///   forge script script/AttackScenarioPart1.s.sol:AttackScenarioPart1
///     --rpc-url $RPC_URL --private-key $DEPLOYER_KEY --broadcast
contract AttackScenarioPart1 is Script {
    function run() external {
        uint256 deployerKey = vm.envUint("DEPLOYER_KEY");
        address poolAddr = vm.envAddress("LENDING_POOL");
        address oracleAddr = vm.envAddress("ORACLE");
        address collateralAddr = vm.envAddress("COLLATERAL");

        address attacker = vm.addr(deployerKey);

        vm.startBroadcast(deployerKey);
        console.log("=== ATTACK SCENARIO PART 1: ORACLE_MANIPULATION_001 ===");
        console.log("Attacker:", attacker);

        MockOracle oracle = MockOracle(oracleAddr);
        ControlledCollateral collateral = ControlledCollateral(collateralAddr);
        LendingPool pool = LendingPool(poolAddr);

        // 1. Mint 1000 collateral to attacker
        console.log("1. Minting 1000 collateral...");
        collateral.mint(attacker, 1000 ether);
        console.log("   Done");

        // 2. Approve pool
        console.log("2. Approving pool...");
        collateral.approve(address(pool), 1000 ether);
        console.log("   Done");

        // 3. Deposit 100 collateral ($100 at $1 price)
        console.log("3. Depositing 100 collateral...");
        pool.deposit(100 ether);
        console.log("   Done");

        // 4. Borrow 75 (max capacity at $1: 75% of $100 = $75)
        console.log("4. Borrowing 75 (max at $1)...");
        pool.borrow(75 ether);
        console.log("   Done");

        // 5. Manipulate oracle price from $1.00 to $1.80
        console.log("5. Setting oracle price to $1.80...");
        oracle.setPrice(address(collateral), 1.8e18);
        console.log("   Done");

        // 6. Borrow 60 more (total debt = 135, within $135 capacity at $1.80)
        console.log("6. Borrowing 60 more (total debt = 135)...");
        pool.borrow(60 ether);
        console.log("   Done - total debt = 135, capacity at $1.80 = 135");

        vm.stopBroadcast();
        console.log("=== PART 1 COMPLETE ===");
        console.log("On-chain events generated. Defense system can now detect the attack.");
        console.log("Note: Step 7 (withdrawal) is NOT executed - it would be BLOCKED by");
        console.log("the SecurityController. The defense simulates the withdrawal consequence");
        console.log("from the events generated by steps 1-6.");
    }
}
